# Generated by Django 3.2.4 on 2021-06-14 20:28

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=users.fields.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
