export default [
  "Palm Lights",
  "Astrid & Rose",
  "Love Life Jewellery",
  "Handtied Box",
  "Garderobe",
  "Home and Soul",
  "Urban Nomads",
  "Story of Source",
  "The Loom collection",
  "Brau Salon",
  "Afrodiva",
  "Charicycles",
  "Shea Global",
  "Yallah Bags",
  "Your Ceramic Store",
  "Lory Lux",
  "Couture Labs",
  "July",
  "Love Spun",
  "Bellavsio Medical",
  "Rahil Hesan",
  "Zero G Beds",
].map(item => item.toLowerCase());
